# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: zyraxi
name: zyraxi
email: zyraxi@outlook.com
location: 中国，四川
company: 哈尔滨工业大学
company_url: https://www.hit.edu.cn/
github_url: https://github.com/zyraxi21
description: 编辑个签，展示我的独特态度
favicon: favicon.png # Image must be in assets/images
repository: zyraxi21/zyraxi21.github.io

url: https://zyraxi21.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  math_engine: mathjax

# Disque
disque: zyraxi.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: 主页

  -
    href: /blog
    label: 博客

  -
    href: /about
    label: 关于

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-81448019-1'


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]

layout: default
comments: true
